### ISSUE TITLE
How do I implement/test this?

### ISSUE THREAD

**Issue by swimnbird** [alladinian/Tuna#3]
I apologize for how new/unfamiliarized with this I am, I'm used to implementing cocoa-pods but I'm very confused on how to test the project files and even implement them. Do I place the project files in an existing project manually and add certain code to implement it, or is there something obvious I'm not seeing?

**Comment by alladinian** [comment]
Hi!
Actually you can check my response to a similar question (I believe it was yours too) [(issue #1) here](https://github.com/alladinian/Tuna/issues/1#issuecomment-860167586)

Please let me know if you need any further assistance with this.
